const programmes = [
  {id:'nova',rank:1,school:'Nova SBE',name:'International Master’s in Management — Marketing / IMC',tier:'冲刺',group:'reach',place:'葡萄牙 · Lisbon',mode:'Round-based',opening:'2027 入学尚未公布；上一周期 2025-11-13 开放',deadline:'2027 轮次待公布；上一周期最终截止 2026-03-23',dateState:'待公布',timeline:'NOV 26',timelineNote:'预计开放窗口',timelineCol:2,source:'https://www.novasbe.unl.pt/en/programs/masters/international-masters-in-management/overview',materials:['英文 CV','动机信 / Motivation Letter','学位证或在读证明','完整成绩单','英语 B2 证明','身份证件','申请费凭证（如适用）','可能要求 GMAT/GRE 或替代证明'],interview:'学校可能安排面试；以申请系统通知为准',note:'官网确认 2026/27 申请已关闭，2027/28 日期尚未发布。不要把上一周期日期当作本轮正式 deadline。'},
  {id:'ucd',rank:2,school:'UCD Smurfit',name:'MSc Digital Marketing',tier:'主申偏冲刺',group:'reach',place:'爱尔兰 · Dublin',mode:'Rolling',opening:'滚动申请；2027 入口以 UCD portal 为准',deadline:'无固定总截止；满位即止，建议尽早',dateState:'滚动录取',timeline:'OCT 26',timelineNote:'建议开始递交',timelineCol:2,source:'https://www.smurfitschool.ie/programmes/masters/mscindigitalmarketing/howtoapply/',materials:['成绩单与原始学历文件','更新版 CV（含工作与课外经历）','两封推荐信（通常学术 + 职业）','英语成绩或合格豁免','两道约 300 词 essay questions','护照 / 身份信息','€70 申请费','其他有助申请的补充材料'],interview:'官网未列统一面试或测试；个案可能补件',note:'官网明确为 rolling basis，课程满位即关闭；完整申请通常约 2–3 周出结果。'},
  {id:'ub',rank:3,school:'Universitat de Barcelona',name:'Master in International Business',tier:'主申偏冲刺',group:'reach',place:'西班牙 · Barcelona',mode:'Rounds',opening:'2027 日历待公布；上一周期首轮 2026-01-19 开放',deadline:'参考上一周期：R1 03-02；R2 04-27；后续轮次以官网为准',dateState:'待公布',timeline:'JAN 27',timelineNote:'预计首轮开放',timelineCol:3,source:'https://web.ub.edu/en/web/estudis/w/masterdegree-md5dc?preRegistration=',materials:['CV','Motivation Letter','本科学位证 / 在读证明','官方成绩单','护照','英语能力证明','可能的推荐信','非欧盟学历的认证/合法化与翻译文件'],interview:'候选人可能被邀请线上面试；以项目通知为准',note:'2026/27 官网曾采用多轮 pre-enrolment。2027 轮次发布后，应优先替换本卡中的参考日期。'},
  {id:'skema',rank:4,school:'SKEMA Business School',name:'MSc International Marketing & Business Development',tier:'主申',group:'target',place:'法国 · 多校区',mode:'Rolling',opening:'通常分月滚动审理；2027 批次待官网确认',deadline:'满位即止；国际生需为签证预留时间',dateState:'滚动录取',timeline:'OCT 26',timelineNote:'尽早建立申请',timelineCol:2,source:'https://www.skema.edu/en/programmes/msc-international-marketing-and-business-development',materials:['CV','Motivation Letter','学位证 / 在读证明','成绩单','英语能力证明','护照照片页','推荐信（如系统要求）','申请费','可能的 GMAT/GRE/TAGE MAGE（依背景）'],interview:'通常包含 admissions interview / selection interview；以邀请为准',note:'SKEMA 项目通常滚动招生，不宜等待所谓“最终截止”。材料要求会按一年制/两年制入口与校区变化。'},
  {id:'bologna',rank:5,school:'University of Bologna / BBS',name:'Digital Marketing & Communication',tier:'主申偏稳妥',group:'safe',place:'意大利 · Bologna',mode:'Call / Deadline',opening:'2027/28 call 尚未发布',deadline:'2027 待公布；2026/27 项目列表显示 9 月截止窗口',dateState:'待公布',timeline:'SPR 27',timelineNote:'等待正式 call',timelineCol:4,source:'https://www.unibo.it/en/study/professional-masters/2026-2027',materials:['在线申请表','CV','Motivation Letter','学位证 / 在读证明','成绩单','英语能力证明','护照 / 身份证件','申请费','GMAT/GRE 或学校测试（如当年 call 要求）'],interview:'通常可能有 aptitude test / interview；以正式 call 为唯一依据',note:'必须以 2027/28 官方 call for applications 为准；该文件会决定硬性文件格式、测试与截止时间。'},
  {id:'polimi',rank:6,school:'POLIMI GSoM',name:'International Master in Marketing Management, Omnichannel & Consumer Analytics',tier:'相对保底',group:'safe',place:'意大利 · Milan',mode:'Rolling',opening:'滚动申请；2027 edition 开放状态需项目页确认',deadline:'滚动审理，招满即止',dateState:'滚动录取',timeline:'NOV 26',timelineNote:'建议首批递交',timelineCol:2,source:'https://www.gsom.polimi.it/en/course/international-master-in-marketing-management-omnichannel-and-consumer-analytics/',materials:['CV','Motivation Letter','学位证 / 在读证明','成绩单','英语能力证明','护照','推荐信（如要求）','申请费','补充招生文件（依个人背景）'],interview:'选拔通常可能包含 motivational interview；以招生团队通知为准',note:'官网明确说明 rolling basis。尽早申请也更有利于奖学金、签证和住宿安排。'}
];
const fields=[['cv','CV 状态'],['ps','PS / ML 状态'],['ref','推荐信状态'],['ielts','IELTS 状态'],['portal','网申状态'],['assessment','Interview / Video / Test'],['submit','最终递交状态']];
const options=['未开始','整理中','初稿完成','修改中','已完成','已递交','不适用'];
const storeKey='masterTracker2027-v1';
let saved=JSON.parse(localStorage.getItem(storeKey)||'{}');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function getStatus(id,key){return saved[id]?.[key]||'未开始'}
function completion(id){const done=fields.filter(([key])=>['已完成','已递交','不适用'].includes(getStatus(id,key))).length;return Math.round(done/fields.length*100)}
function renderTimeline(){document.querySelector('#timelineItems').innerHTML=programmes.map(p=>`<a class="timeline-event" href="#${p.id}" style="grid-column:${p.timelineCol}"><small>${p.timeline}</small><strong>${esc(p.school)}</strong><em>${esc(p.timelineNote)}</em></a>`).join('')}
function statusSelect(p,key,label){const value=getStatus(p.id,key);return `<div class="status-item"><label for="${p.id}-${key}">${label}</label><select id="${p.id}-${key}" data-id="${p.id}" data-key="${key}">${options.map(o=>`<option${o===value?' selected':''}>${o}</option>`).join('')}</select></div>`}
function card(p){const pct=completion(p.id), date=saved[p.id]?.date||'',notes=saved[p.id]?.notes||'';return `<article class="program-card" id="${p.id}" data-group="${p.group}"><div class="card-summary" role="button" tabindex="0" aria-expanded="false"><div class="rank">0${p.rank}</div><div class="card-title"><small>${p.tier} · ${p.school}</small><h3>${p.name}</h3><div class="card-meta"><span>${p.place}</span><span>${p.mode}</span><span>${p.dateState}</span></div></div><div class="card-side"><div class="mini-progress"><strong>${pct}%</strong><div><span style="width:${pct}%"></span></div></div><span class="toggle">+</span></div></div><div class="card-detail"><div class="detail-grid"><div class="facts"><div class="fact"><label>开放时间</label><p>${p.opening}</p></div><div class="fact"><label>Deadline / Round</label><p>${p.deadline}<span class="tag ${p.dateState==='待公布'?'warn':''}">${p.dateState}</span></p></div><div class="fact"><label>Interview / Video / Test</label><p>${p.interview}</p></div><div class="fact"><label>重要判断</label><p>${p.note}</p></div></div><div><div class="materials"><h4>材料清单</h4><ul class="checklist">${p.materials.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="tracker"><h4>进度状态</h4><div class="status-grid">${fields.map(f=>statusSelect(p,...f)).join('')}<div class="status-item"><label for="${p.id}-date">最终递交日期</label><input class="submission-date" id="${p.id}-date" type="date" value="${esc(date)}" data-id="${p.id}" data-key="date"></div></div><textarea class="notes" aria-label="${p.school} 备注" placeholder="记录账号、推荐人、补件要求或下一步……" data-id="${p.id}" data-key="notes">${esc(notes)}</textarea></div></div><div class="detail-actions"><a class="official-link" href="${p.source}" target="_blank" rel="noopener">打开官网核验 ↗</a><span class="save-note">修改后自动保存在当前设备</span></div></div></article>`}
function renderPrograms(filter='all'){const list=filter==='all'?programmes:programmes.filter(p=>p.group===filter);document.querySelector('#programList').innerHTML=list.map(card).join('');bindCards();updateSummary()}
function bindCards(){document.querySelectorAll('.card-summary').forEach(el=>{const toggle=()=>{const card=el.closest('.program-card');card.classList.toggle('open');el.setAttribute('aria-expanded',card.classList.contains('open'))};el.addEventListener('click',toggle);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})});document.querySelectorAll('select,input,textarea').forEach(el=>{el.addEventListener('click',e=>e.stopPropagation());el.addEventListener('change',saveField);el.addEventListener('input',e=>{if(e.target.tagName==='TEXTAREA')saveField(e)})})}
function saveField(e){const{id,key}=e.target.dataset;saved[id]={...(saved[id]||{}),[key]:e.target.value};localStorage.setItem(storeKey,JSON.stringify(saved));const cardEl=document.getElementById(id);const pct=completion(id);cardEl.querySelector('.mini-progress strong').textContent=pct+'%';cardEl.querySelector('.mini-progress span').style.width=pct+'%';updateSummary()}
function updateSummary(){const total=Math.round(programmes.reduce((a,p)=>a+completion(p.id),0)/programmes.length);document.querySelector('#overallProgress').textContent=total+'%';document.querySelector('#globalProgressBar').style.width=total+'%';document.querySelector('#nextCount').textContent=programmes.filter(p=>completion(p.id)<100).length}
document.querySelectorAll('.filters button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPrograms(b.dataset.filter)}));
document.querySelector('#resetBtn').addEventListener('click',()=>{if(confirm('确认清除当前设备中保存的所有申请状态与备注？')){localStorage.removeItem(storeKey);saved={};renderPrograms()}});
document.querySelector('#sourceLinks').innerHTML=programmes.map(p=>`<a href="${p.source}" target="_blank" rel="noopener">${p.school} 官网 ↗</a>`).join('');
renderTimeline();renderPrograms();
